### ISSUE TITLE
Question: Additional names

### ISSUE THREAD

**Issue by thebigcosinus** [schwamster/serverless-certificate-creator#11]
Hi, 

Thanks for your great plugins.

Is it possible to add  Additional names 
I would like my domain to be domain.com and add *.domain.com in additional names.

Is that possible ?

Thanks

**Comment by schwamster** [comment]
Hi @thebigcosinus ,

should be possible -> https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ACM.html#requestCertificate-property

A new option called subjectAlternativeNames could be added to the configuration with a list of alternative names: 

```yaml
  customCertificate:
    certificateName: 'somedomain.com'
    hostedZoneName: 'somedomain.io.'
    subjectAlternativeNames :
      - 'somedomain.net'
      - 'someotherdomain.com'
```

Is this what you are looking for?

**Comment by thebigcosinus** [comment]
Yes exactly I'm looking for subjectAlternativeNames

**Comment by schwamster** [comment]
@thebigcosinus I added a rc for this would you be so kind and see if this will do the trick?

npm i serverless-certificate-creator@rc-SubjectAlternativeNames

**Comment by schwamster** [comment]
fyi - serverless-certificate-creator@rc-SubjectAlternativeNames also contains your other feature request now - certificate name (or rather tags):

so you should be able to test something like this with the current rc

```yaml
  customCertificate:
    certificateName: 'somedomain.com'
    hostedZoneName: 'somedomain.io.'
    subjectAlternativeNames :
      - 'somedomain.net'
      - 'someotherdomain.com'
    tags:
      Name: 'somedomain.com'
      Environment: 'prod'
```

**Comment by thebigcosinus** [comment]
Hi, 
I cannot add additional names. I ve got he error 
`The request contains an invalid set of changes for a resource record set 'CNAME _....`

I ve try différent names
*.mydomain.com
dev.mydomain.com

No success.

Using the aws console I was able to add additional names

**Comment by schwamster** [comment]
Strange. I cannot seem to be able to reproduce your issue. I get it to work with the following configuration

```yaml
  customCertificate:
    certificateName: 'si10.greenelephant.io'
    idempotencyToken: 'si10greenelephantio'
    hostedZoneName: 'greenelephant.io.'
    subjectAlternativeNames :
      - '*.greenelephant.io'
      - 'dev.greenelephant.io'
    tags:
      Name: 'si10.greenelephant.io'
      Environment: 'prod'
```

This seems more of an problem with the aws sdk or the selected parameters. Have you checked out if your subjectAlternativeNames are in line with the rules -> https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ACM.html#requestCertificate-property
Any chance of getting a more detailed error msg and/or your config?
