### ISSUE TITLE
Certificate Name is empty

### ISSUE THREAD

**Issue by thebigcosinus** [schwamster/serverless-certificate-creator#12]
Hi,

When using the plugin the certificate name in ACM console is empty

How can I set a name to my certificate ?

Thanks

**Comment by schwamster** [comment]
Hi @thebigcosinus ,

I believe this can be done by adding a tag to the certificate (key: Name). The sdk supports this: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/ACM.html#addTagsToCertificate-property

This api call could be added after the cert has been requested. What name do you typically add? The domain name? Should the existing certificateName option of the plugin be used for this or do you think it is better to have a generic Tags option? I kind of prefer a generic tags option like this:

```yaml
  customCertificate:
    certificateName: 'somedomain.com'
    hostedZoneName: 'somedomain.io.'
    tags:
      Name: 'somedomain.com'
      Environment: 'prod'
```
