### ISSUE TITLE
Error when we create certificate without hosted zone

### ISSUE THREAD

**Issue by GerardPaligot** [schwamster/serverless-certificate-creator#2]
Hello,

When I try to create a certificate without an hosted zone, I got a stack trace from your plugin.

```
➜  products git:(master) ✗ serverless create-cert --stage prod --region eu-west-1
Serverless: Trying to create certificate for api-eu.instorebff.net in eu-west-1 ...
Serverless: requested cert: arn:aws:acm:eu-west-1:397905682806:certificate/ea6d06cc-c92b-487a-8a80-e88dab500256
Serverless: got cert info: arn:aws:acm:eu-west-1:397905682806:certificate/ea6d06cc-c92b-487a-8a80-e88dab500256 - PENDING_VALIDATION
Serverless: certificate validation failed
problem no hosted zone for domain found
Serverless: could not get cert info
problem no hosted zone for domain found
Serverless: could not request cert
problem no hosted zone for domain found
Serverless: could not get certs
problem no hosted zone for domain found
Unhandled rejection Error: no hosted zone for domain found
    at module.exports.logError (/usr/local/lib/node_modules/serverless/lib/classes/Error.js:92:11)
    at initializeErrorReporter.then.catch.e (/usr/local/lib/node_modules/serverless/bin/serverless:62:3)
    at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
    at process.topLevelDomainCallback (domain.js:121:23)
```

But the certificate is well created behind this error. :/

My configuration from serverless file:

```
  customDomain:
    basePath: ${self:service}
    domainName: ${self:custom.domains.${self:custom.stage}.${self:custom.region}}
    certificateName: ${self:custom.domains.${self:custom.stage}.${self:custom.region}}
    stage: ${self:custom.stage}
    createRoute53Record: true
    endpointType: 'regional'
  customCertificate:
    certificateName: ${self:custom.domains.${self:custom.stage}.${self:custom.region}}
    region: ${self:custom.region}
```
