### ISSUE TITLE
wildcard and basename certificates fails to create route53 record

### ISSUE THREAD

**Issue by jesusch** [schwamster/serverless-certificate-creator#46]
given the following config:

```
custom:
  customCertificate:
    certificateName: example.com
    subjectAlternativeNames:
    - '*.example.com'
```

serverless-certificate-creator successfully the ACM certificate as pending
while trying to create CNAMEs it fails
the reason I found was:
the certificate returns 2 validation records to be created
but both records are identical
then serverless-certificate-creator tries to bulkcreate those 2 records, but route53 refuses it because of duplicate records.

serverless-certificate-creator could/should verify the record-list and unique() them before sending it to the route53 api?
