### ISSUE TITLE
Creating multiple certificates for different regions

### ISSUE THREAD

**Issue by spullara** [schwamster/serverless-certificate-creator#47]
I'd like to create multiple certificates for different regions as a load balancer needs a region local certificate and api gateway needs one created for us-east-1. Right now it only supports making 1 certificate.

**Comment by ademoverflow** [comment]
Need this also for the exact same reason.

**Comment by dezeroku** [comment]
Were you able to find a solution for this (hit the same issue with cloudfront)? I'd consider forking/sending a PR, if there's no easy workaround.

**Comment by spullara** [comment]
There was no workaround for me. Turns out API Gateway does allow local certificates. So for cloudfront you would still need a separate one in us-east-1.

**Comment by dezeroku** [comment]
I've created a PR for this, following configuration works for me with serverless 3:
```
  customCertificate:
    # This is a cert for domain-manager, local apigateway, region cert is fine
    -
      certificateName: ${self:custom.userConfig.apiDomain}
      hostedZoneNames: ${self:custom.userConfig.baseDomain}.
      region: ${self:provider.region}
      enabled: true
      rewriteRecords: false
    # This is a cert for CloudFront, so it has to be in us-east-1
    -
      certificateName: ${self:custom.userConfig.frontDomain}
      hostedZoneNames: ${self:custom.userConfig.baseDomain}.
      region: us-east-1
      enabled: true
      rewriteRecords: false
    # This is a cert for Cognito Domain, has to be in us-east-1
    -
      certificateName: auth.${self:custom.userConfig.frontDomain}
      hostedZoneNames: ${self:custom.userConfig.baseDomain}.
      region: us-east-1
      enabled: true
      rewriteRecords: false
```
and generates certificates in chosen regions.

Getting the ARN as variable gets more verbose (and duplicated a bit), but also works. E.g. to get ARN of the certificate that's first in the array you'd use
`${certificate(${self:custom.customCertificate.0.certificateName}, '0'):CertificateArn}`

Looking at the project history there were no PRs merged lately, so I've also [published the package in npm](https://www.npmjs.com/package/@dezeroku/serverless-certificate-creator), if someone wants to try it.
