### ISSUE TITLE
"TypeError: Cannot read property 'options' of undefined" with Serverless >= 2.38.0

### ISSUE THREAD

**Issue by davelosert** [schwamster/serverless-certificate-creator#49]
When using this plugin (current version 1.5.3) with serverless >= 2.38.0, we get the following error:
(I masked the actual paths with **)
```
  TypeError: Cannot read property 'options' of undefined
      at module.exports (/builds/**/node_modules/serverless/lib/utils/telemetry/generatePayload.js:133:66)
      at runNextTicks (internal/process/task_queues.js:58:5)
      at processImmediate (internal/timers.js:434:9)
      at async PluginManager.run (/builds/**/node_modules/serverless/lib/classes/PluginManager.js:607:35)
      at async Serverless.run (/builds/**/node_modules/serverless/lib/Serverless.js:325:5)
      at async /usr/local/lib/node_modules/serverless/scripts/serverless.js:634:9
```

Our settings:
```
  customDomain:
    domainName: ${env:DOMAIN_NAME}
    certificateName: ${env:CERT_NAME}
    basePath: ""
    stage: ${self:provider.stage}
    endpointType: "regional"
    region: ${self:provider.region}
    createRoute53Record: true

  customCertificate:
    certificateName: ${env:CERT_NAME}
    hostedZoneNames: ${env:HOSTED_ZONE_NAMES}
    region: ${self:provider.region}
    stage: ${self:provider.stage}
    enabled: true
    rewriteRecords: fals
```

We tried it with 2.38.0 through to 2.39.2 with the same error each time. Other sls commands (`sls print` or `sls deploy`) are working fine.

Other plugins used are:
- serverless-add-api-key: "4.2.0",
- serverless-certificate-creator: "1.5.3",
- serverless-domain-manager: "5.1.0",
- serverless-plugin-aws-alerts: "1.7.3",
- serverless-plugin-cloudwatch-dashboard: "1.2.0",
- serverless-python-requirements: "5.1.1" 

Do you have an idea what causes this?
